### PR TITLE
HADOOP-14382 Remove usages of MoreObjects.toStringHelper.

### PR DESCRIPTION
**Pull request by nartmal**
https://github.com/apache/hadoop/blob/4e6bbd049dead7008942bda09dfd54542c407f48/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/metrics2/MetricsTag.java

https://issues.apache.org/jira/browse/HADOOP-14382

**Please note I also had to include a bump of javac 1.7 -> 1.8 in pom.xml**

### CODE REVIEW

**Comment by sjrand** [comment]
I checked the tests results and this basically seems good. There are some spurious-looking failures, but that's nothing new. @ash211 or @robert3005 , any concerns with merging this? Requiring Java 8 should be okay for this particular repo, though of course not upstream (until hadoop 3 that is).

**Comment by ash211** [comment]
This patch is small enough that we could likely rewrite with Java 7 APIs to not have to get the Java bump.  I guess I see three paths forward:

- take this cherry pick from hadoop-3.0 and bump to Java 8
- rewrite this patch and stay on Java 7, which forks us from upstream Hadoop
- make no change

Can we go with option 3 and wait until hadoop 3 to pull in this change?

**Comment by sjrand** [comment]
I would love to go with option 3, but we need to stop relying on methods that go away in more recent Guava versions due to a different library relying on Guava 21. @nartmal has more details.

While Java 8 (first option in your list) is a fairly major divergence from upstream Hadoop, it allows us to maintain our "backports or reverts only" policy, and I don't think it has a downside given the very specific way in which this fork is used.

**Comment by nartmal** [comment]
Option 3 is a possibility if we are willing to accept the possibility of busted metric classes. AFAIK, their toString methods are only invoked when log.info is called so this might be OK. I can fix w/ sls-logging PR.

I don't think there is much we can do around this guava issue, but I think we have always (or at least for > 1 year) had broken parts in hadoop-common since guava11->18 included the MoreObjects move (https://github.com/google/guava/wiki/Release18#significant-api-additions-and-changes).

So yeah... we can stick with what we have and reject this PR. This wasn't an issue until sls-logging was introduced. Just remember not to use any metrics2 objects.

**Comment by nartmal** [comment]
sls-logging fix went through and fixed our issue. No longer need this PR. Its still kind of icky that a guava18 bump still breaks stuff in the metrics2 package but whatever... 

AFAIK metrics2.MetricsRegistry seems to only be invoked on S3AInstrumentation and AzureFileSystemInstrumentation,

**Comment by sjrand** [comment]
Not that it matters anymore, but looks like this got fixed upstream in https://issues.apache.org/jira/browse/HADOOP-14891.

**Pull request closed without merging**
