### PR TITLE
HADOOP-10101. Guava 11 -> 21 bump

### PR DESCRIPTION
**Pull request by nartmal**
cherry-pick of https://github.com/apache/hadoop/commit/84ddedc0b2d58257d45c16ee5e83b15f94a7ba3a

Changes:
- ``Enums.valueOfFunction`` -> ``Enums.stringConverter`` (removed in guava18)
-  ``Throwables.propagate(t);`` -> ``throw t`` (deprecated function, but not required change)
- package move of ``Objects`` -> ``MoreObjects``(moved in guava18, bulk of changes)
- ``Sets.newSetFromMap`` -> ``Collections.newSetFromMap`` (deprecated function, but not required change)
- ``Iterators.emptyIterator`` -> ``java.util.Collections.emptyIterator();`` (required change, Iterators.emptyIterator no longer public as of guava 20)
- `` ComparisonChain.start().compare`` -> ``ComparisonChain.start().compareFalseFirst`` (deprecated function, but not required change)
- ``MoreExecutors.sameThreadExecutor();`` -> ``MoreExecutors.newDirectExecutorService();`` (https://github.com/google/guava/wiki/Release21#commonutilconcurrent)
``CharMatcher.ASCII`` and ``CharMatcher.WHITESPACE`` moved to ``CharMatcher.ascii()`` and ``CharMatcher.whitespace()`` (deprecated constants, equivalent changes, not required change)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/hadoop](https://github.com/palantir/hadoop), @nartmal! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by sjrand** [comment]
I was initially pretty skeptical, but this might actually be okay. Unlike Apache Hadoop, we don't have to worry about many hundreds of downstream projects that depend on `hadoop-client`; as long as Spark and some internal HDFS/YARN client applications aren't broken by this change, then it seems fine IMO.

@ash211 , @robert3005 , thoughts? (Motivation in case you haven't seen it is a separate project depending on Guava 21)

EDIT: And of course we have to verify that this patch, which targeted 3.0.0-alpha4, makes sense against 2.8.x. It apparently cherry-picked cleanly, but that doesn't guarantee that it works.

**Comment by sjrand** [comment]
Also, @nartmal , I suspect that you might have to sign the CLA in order to trigger CI. It's run on previous PRs, but doesn't seem to be running on this one.

**Comment by nartmal** [comment]
It wasn't 100% clean cherry pick, I had to manually resolve the following:

```
	both modified:   hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/RMAppManager.java
	both modified:   hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/fair/AllocationFileLoaderService.java
	both modified:   hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/scheduler/fair/QueueManager.java
```

Only ``RMAppManager.java`` was slightly above trivial. The rest was very trivial.

A side note is that we can minimize changes further by choosing to still use deprecated methods if this helps maintain maintenance of further backported patches.

Poking at the changes listed above, only ``Enums.valueOfFunction`` to ``Enums.stringConverter`` had drastic code changes. The rest looked either very safe or explicitly called out in guava release notes

**Comment by nartmal** [comment]
``AllocationFileLoaderService.java``and ``QueueManager.java`` had unnecessary usages of ``CharMatcher``. I'm assuming that a previous commit made this change and they needed to switch off of deprecated constants.

RMAppManager.java had a large conflict:
```
  @Override
  public void handle(RMAppManagerEvent event) {
    ApplicationId applicationId = event.getApplicationId();
    LOG.debug("RMAppManager processing event for " 
        + applicationId + " of type " + event.getType());
    switch(event.getType()) {
      case APP_COMPLETED: 
      {
        finishApplication(applicationId);
        logApplicationSummary(applicationId);
        checkAppNumCompletedLimit(); 
      } 
      break;
<<<<<<< HEAD
      default:
        LOG.error("Invalid eventtype " + event.getType() + ". Ignoring!");
=======
    case APP_MOVE :
      ... couple hundred lines of new functionality ...
>>>>>>> 84ddedc0b2... HADOOP-10101. Update guava dependency to the latest version. (ozawa)
      }
  }
}
```

**Comment by nartmal** [comment]
Per email thread, we can try only moving to guava18 rather than guava21.

``Enums.stringConverter`` and ``MoreObjects`` changes (from above) are the only ones required. We can choose to move away from deprecated methods as well.

**Comment by nartmal** [comment]
see https://github.com/google/guava/wiki/Release19#commonutilconcurrent for notes on Futures.get removal.

**Comment by nartmal** [comment]
dependency ``org.apache.curator.framework.listen.ListenerContainer`` in curator-framework-2.7.1 depends on ``MoreExecutors.sameThreadExecutor();`` (removed in guava 21). 

Looks like we would also need https://github.com/apache/hadoop/commit/74af0bdf68d56f02e92dad2411b26d1cde3dc703 which is what is on 3.0.0-alpha4

They shaded MoreExecutors in the later version of apache.curator.framework

**Comment by nartmal** [comment]
for some reason its using my circleci account instead of palantirs...

**Comment by nartmal** [comment]
closing in favor of https://github.com/palantir/hadoop/pull/27

**Pull request closed without merging**
